//created on: 2013-11-22
package rules

//list any import classes here.
import com.sample.DroolsTest.*


//declare any global variables here

import pl.put.poznan.*;


rule "start"
	salience 1000
	when
       
    then
        insert(Pytanie.zadaj("polozenie"));
        insert(new Fakt("niejednoznacznie", true));

end

rule "wyspiarski"
	salience 100
	when
		Fakt(klucz=="polozenie", tekst != "Wschod")
		Fakt(klucz=="niejednoznacznie", prawda)
	then
		Fakt o = Pytanie.zadaj("wyspiarski");
        insert(o);
        if (o.getPrawda())
        	insert(new Fakt("ma_morze", true));
end

rule "wladza"
	when
		o : Fakt(klucz=="niejednoznacznie", prawda)
	then
		Fakt p = Pytanie.zadaj("wladza");
		if (p.getTekst().equals("Kapitan") || p.getTekst().equals("Papież")){
			o.setPrawda(false);
			update(o);
		}
		insert(p);
end

rule "euro"
	when
		o : Fakt(klucz=="niejednoznacznie", prawda)
	then
		insert(Pytanie.zadaj("euro"));
end

rule "samochody"
	salience 100
	when
		o : Fakt(klucz=="niejednoznacznie", prawda)
	then
		insert(Pytanie.zadaj("samochody"));

end

rule "czy_szwecja"
	when
		Fakt(klucz=="polozenie", tekst == "Polnoc")
		o : Fakt(klucz=="niejednoznacznie", prawda)
	then
		insert(Pytanie.zadaj("szwecja"));
end

rule "czy_wodka"
	when
		Fakt(klucz=="polozenie", tekst == "Polnoc")
		o : Fakt(klucz=="niejednoznacznie", prawda)
		Fakt(klucz=="szwecja", !prawda)
	then
		insert(Pytanie.zadaj("czy_wodka"));
end

rule "marka_samochodu_w"
	when
		Fakt(klucz=="polozenie", tekst == "Zachod")
		Fakt(klucz=="samochody", prawda)
		o : Fakt(klucz=="niejednoznacznie", prawda)
	then
		Fakt p = Pytanie.zadaj("marka_samochodu_w");
		insert(p);
		if (p != null) {
			o.setPrawda(false);
			update(o);
		}
end

rule "marka_samochodu_e"
	when
		Fakt(klucz=="polozenie", tekst == "Wschod")
		Fakt(klucz=="samochody", prawda)
		o : Fakt(klucz=="niejednoznacznie", prawda)
	then
		Fakt p = Pytanie.zadaj("marka_samochodu_e");
		insert(p);
		if (p != null) {
			o.setPrawda(false);
			update(o);
		}
end

rule "ma_morze"
	when
		Fakt(klucz=="wyspiarski", !prawda) or
		Fakt(klucz=="polozenie", tekst == "Wschod")
		o : Fakt(klucz=="niejednoznacznie", prawda)
	then
		insert(Pytanie.zadaj("ma_morze"));
end
		
rule "morze_n"
	when
		Fakt(klucz=="ma_morze", prawda)
		Fakt(klucz=="polozenie", tekst=="Polnoc")
	then
		insert(Pytanie.zadaj("morze_n"));
end
		
rule "morze_w"
	when
		Fakt(klucz=="ma_morze", prawda)
		Fakt(klucz=="polozenie", tekst=="Zachod")
	then
		insert(Pytanie.zadaj("morze_w"));
end
		
rule "morze_e"
	when
		Fakt(klucz=="ma_morze", prawda)
		Fakt(klucz=="polozenie", tekst=="Wschod")
	then
		insert(Pytanie.zadaj("morze_e"));
end
		
rule "morze_s"
	when
		Fakt(klucz=="ma_morze", prawda)
		Fakt(klucz=="polozenie", tekst=="Poludnie")
	then
		insert(Pytanie.zadaj("morze_s"));
end

rule "piwo_n"
	when
		Fakt(klucz=="polozenie", tekst=="Polnoc")
		o : Fakt(klucz=="niejednoznacznie", prawda)
	then
		Fakt p = Pytanie.zadaj("piwo_n");
		insert(p);
		if (p != null) {
			o.setPrawda(false);
			update(o);
		}
end

rule "piwo_s"
	when
		Fakt(klucz=="polozenie", tekst=="Poludnie")
		o : Fakt(klucz=="niejednoznacznie", prawda)
	then
		Fakt p = Pytanie.zadaj("piwo_s");
		insert(p);
	 	if (p != null) {
			o.setPrawda(false);
			update(o);
		}
end

rule "piwo_e"
	when
		Fakt(klucz=="polozenie", tekst=="Wschod")
		o : Fakt(klucz=="niejednoznacznie", prawda)
	then
		Fakt p = Pytanie.zadaj("piwo_e");
		insert(p);
		if (p != null) {
			o.setPrawda(false);
			update(o);
		}
end

rule "piwo_w"
	when
		Fakt(klucz=="polozenie", tekst=="Zachod")
		o : Fakt(klucz=="niejednoznacznie", prawda)
	then
		Fakt p = Pytanie.zadaj("piwo_w");
		insert(p);
		if (p != null) {
			o.setPrawda(false);
			update(o);
		}
end

rule "balkanskie"
	when
		Fakt(klucz=="polozenie", tekst=="Poludnie")
		o : Fakt(klucz=="niejednoznacznie", prawda)
	then
		insert(Pytanie.zadaj("balkanskie"));
end

rule "czy_grecja"
	salience 100
	when
		Fakt(klucz=="balkanskie", prawda)
		o : Fakt(klucz=="niejednoznacznie", prawda)
	then
		Fakt p = Pytanie.zadaj("grecja");
		insert(p);
		if (p.getPrawda()){
			o.setPrawda(false);
			update(o);
		}
end

rule "czy_turcja"
	salience 99
	when
		Fakt(klucz=="balkanskie", prawda)
		o : Fakt(klucz=="niejednoznacznie", prawda)
	then
		Fakt p = Pytanie.zadaj("turcja");
		insert(p);
		if (p.getPrawda()){
			o.setPrawda(false);
			update(o);
		}
end

rule "stolica_balkany"
	salience 10
	when
		Fakt(klucz=="balkanskie", prawda)
		o : Fakt(klucz=="niejednoznacznie", prawda)
	then
		insert(Pytanie.zadaj("stolica_balkany"));
		o.setPrawda(false);
		update(o);
end

rule "graniczy_polska_e"
	when
		Fakt(klucz=="polozenie", tekst=="Wschod")
		o : Fakt(klucz=="niejednoznacznie", prawda)
	then
		insert(Pytanie.zadaj("graniczy_polska"));
end

rule "graniczy_polska_w"
	when
		Fakt(klucz=="polozenie", tekst=="Zachod")
		o : Fakt(klucz=="niejednoznacznie", prawda)
	then
		Fakt p = Pytanie.zadaj("graniczy_polska");
		insert(p);
		if (p.getPrawda() ) {
			o.setPrawda(false);
			update(o);
		}
end