//created on: 2013-11-22
package rules

//list any import classes here.
import com.sample.DroolsTest.*


//declare any global variables here




rule "pyt1"

    when
       
    then
        insert(Pytanie.zadaj("id_1"));

end

rule "pyt2"
  
    when
        Odpowiedz(pytanie == "id_1", tekst == "tak")
    then
        insert(Pytanie.zadaj("id_2"));

end

rule "pyt3"
	when
		Odpowiedz(pytanie == "id_2", tekst == "Ba¸tyckie")
	then
		insert(Pytanie.zadaj("id3"));
end
		
rule "pyt4"
	when
		Odpowiedz(pytanie == "id_2", tekst == "år—dziemne")
	then
		insert(Pytanie.zadaj("id4"));
end	
		
		
		
		
		
		
		
		