//created on: 2013-11-22
package rules

//list any import classes here.
import com.sample.DroolsTest.*


//declare any global variables here
import pl.put.poznan.*;

rule "Znamy Odpowiedz"
	salience 10001
	when
		Fakt(klucz=="panstwo", $panstwo : tekst)
	then
		Fakt.oglos($panstwo);
		drools.halt();
end

rule "Albania"
	salience 10000
	when
		Fakt(klucz=="stolica", tekst=="Tirana")
	then
		insert(new Fakt("panstwo", "Albania"));
end

rule "Andora"
	salience 10000
	when
		Fakt(klucz=="polozenie", tekst=="Europa zachodnia")
		Fakt(klucz=="wladza", tekst=="Monarcha")
		Fakt(klucz=="euro", prawda)
	then
		insert(new Fakt("panstwo", "Andora"));
end

rule "Austria"
	salience 10000
	when
		Fakt(klucz=="polozenie", tekst=="Europa zachodnia")
		Fakt(klucz=="euro", prawda)
		
		Fakt(klucz=="piwo", tekst in ("Stiegl", "Zipfer"))
	then
		insert(new Fakt("panstwo", "Austria"));
end

rule "Belgia"
	salience 10000
	when
		Fakt(klucz=="polozenie", tekst=="Europa zachodnia")
		Fakt(klucz=="wladza", tekst=="Monarcha")
		Fakt(klucz=="euro", prawda)
		Fakt(klucz=="piwo", tekst=="Duvel")
	then
		insert(new Fakt("panstwo", "Belgia"));
end

rule "Bialorus"
	salience 10000
	when
		Fakt(klucz=="polozenie", tekst=="Europa wschodnia")
	then
		insert(new Fakt("panstwo", "Bialorus"));
end

rule "Bosnia i Hercegowina"
	salience 10000
	when
		(or
			Fakt(klucz=="piwo", tekst=="Nektar")
			Fakt(klucz=="stolica", tekst=="Sarajewo")
		)
	then
		insert(new Fakt("panstwo", "Bosnia i Hercegowina"));
end

rule "Bulgaria"
	salience 10000
	when
		(or
			Fakt(klucz=="piwo", tekst=="Szumensko")
			Fakt(klucz=="stolica", tekst=="Sofia")
		)
	then
		insert(new Fakt("panstwo", "Bulgaria"));
end

rule "Chorwacja"
	salience 10000
	when
		Fakt(klucz=="stolica", tekst=="Zagrzeb")
	then
		insert(new Fakt("panstwo", "Chorwacja"));
end

rule "Czarnogora"
	salience 10000
	when
		Fakt(klucz=="stolica", tekst=="Podgorica")
	then
		insert(new Fakt("panstwo", "Czarnogora"));
end

rule "Czechy"
	salience 10000
	when
		Fakt(klucz=="polozenie", tekst=="Europa wschodnia")
		Fakt(klucz=="piwo", tekst=="Staropramen")
	then
		insert(new Fakt("panstwo", "Czechy"));
end

rule "Cypr"
	salience 10000
	when
		(or
			(and
				Fakt(klucz=="polozenie", tekst=="Europa poludniowa")
				Fakt(klucz=="wyspiarski", prawda)
			)
			Fakt(klucz=="piwo", tekst=="Keo")
		)
	then
		insert(new Fakt("panstwo", "Cypr"));
end

rule "Dania"
	salience 10000
	when
		Fakt(klucz=="polozenie", tekst=="Europa zachodnia")
		Fakt(klucz=="wladza", tekst=="Monarcha")
		Fakt(klucz=="piwo", tekst=="Tuborg")
	then
		insert(new Fakt("panstwo", "Dania"));
end

rule "Estonia"
	salience 10000
	when
		Fakt(klucz=="polozenie", tekst=="Europa wschodnia")
		Fakt(klucz=="euro", prawda)
	then
		insert(new Fakt("panstwo", "Estonia"));
end

rule "Finlandia"
	salience 10000
	when
		(or
			Fakt(klucz=="czy_wodka", prawda)
			Fakt(klucz=="piwo", tekst=="Sahti")
		)
	then
		insert(new Fakt("panstwo", "Finlandia"));
end

rule "Francja"
	salience 10000
	when
		Fakt(klucz=="polozenie", tekst=="Europa zachodnia")
		Fakt(klucz=="euro", prawda)
		Fakt(klucz=="samochody", prawda)
		Fakt(klucz=="marka_samochodu", tekst in ("Citroen", "Peugeot"))
	then
		insert(new Fakt("panstwo", "Francja"));
end

rule "Grecja"
	salience 10000
	when
		(or
			Fakt(klucz=="grecja", prawda)
			Fakt(klucz=="piwo", tekst=="Zorbas")
		)
	then
		insert(new Fakt("panstwo", "Grecja"));
end

rule "Hiszpania"
	salience 10000
	when
		Fakt(klucz=="marka_samochodu", tekst == "Seat")
	then
		insert(new Fakt("panstwo", "Hiszpania"));
end

rule "Holandia"
	salience 10000
	when
		Fakt(klucz=="polozenie", tekst=="Europa zachodnia")
		Fakt(klucz=="wladza", tekst=="Monarcha")
		Fakt(klucz=="euro", prawda)
		Fakt(klucz=="piwo", tekst=="Grolsch")
	then
		insert(new Fakt("panstwo", "Holandia"));
end

rule "Irlandia"
	salience 10000
	when
		Fakt(klucz=="polozenie", tekst=="Europa zachodnia")
		Fakt(klucz=="wyspiarski", prawda)
		Fakt(klucz=="wladza", tekst=="Monarcha")
		Fakt(klucz=="euro", prawda)
	then
		insert(new Fakt("panstwo", "Irlandia"));
end

rule "Islandia"
	salience 10000
	when
		(or
			(and
				Fakt(klucz=="polozenie", tekst=="Europa polnocna")
				Fakt(klucz=="wyspiarski", prawda)
			)
			Fakt(klucz=="piwo", tekst=="Vinbudin")
		)
	then
		insert(new Fakt("panstwo", "Islandia"));
end

rule "Kosowo"
	salience 10000
	when
		Fakt(klucz=="polozenie", tekst=="Europa poludniowa")
		Fakt(klucz=="stolica", tekst=="Prisztina")
	then
		insert(new Fakt("panstwo", "Kosowo"));
end
rule "Kazachstan"
	salience 10000
	when
		Fakt(klucz=="polozenie", tekst=="Europa wschodnia")
	then
		insert(new Fakt("panstwo", "Kazachstan"));
end

rule "Liechtenstein"
	salience 10000
	when
		Fakt(klucz=="polozenie", tekst=="Europa zachodnia")
		Fakt(klucz=="wladza", tekst=="Monarcha")
	then
		insert(new Fakt("panstwo", "Liechtenstein"));
end

rule "Litwa"
	salience 10000
	when
		Fakt(klucz=="polozenie", tekst=="Europa wschodnia")
	then
		insert(new Fakt("panstwo", "Litwa"));
end

rule "Luksemburg"
	salience 10000
	when
		Fakt(klucz=="polozenie", tekst=="Europa zachodnia")
		Fakt(klucz=="wladza", tekst=="Monarcha")
		Fakt(klucz=="euro", prawda)
	then
		insert(new Fakt("panstwo", "Luksemburg"));
end

rule "Lotwa"
	salience 10000
	when
		Fakt(klucz=="polozenie", tekst=="Europa wschodnia")
	then
		insert(new Fakt("panstwo", "Lotwa"));
end

rule "Macedonia"
	salience 10000
	when
		Fakt(klucz=="polozenie", tekst=="Europa poludniowa")
		Fakt(klucz=="stolica", tekst=="Skopje")
	then
		insert(new Fakt("panstwo", "Macedonia"));
end

rule "Malta"
	salience 10000
	when
		Fakt(klucz=="polozenie", tekst=="Europa poludniowa")
		Fakt(klucz=="euro", prawda)
	then
		insert(new Fakt("panstwo", "Malta"));
end

rule "Moldawia"
	salience 10000
	when
		Fakt(klucz=="polozenie", tekst=="Europa wschodnia")
	then
		insert(new Fakt("panstwo", "Moldawia"));
end

rule "Monako"
	salience 10000
	when
		Fakt(klucz=="polozenie", tekst=="Europa poludniowa")
		Fakt(klucz=="wladza", tekst=="Monarcha")
		Fakt(klucz=="euro", prawda)
	then
		insert(new Fakt("panstwo", "Monako"));
end

rule "Niemcy"
	salience 10000
	when
		Fakt(klucz=="polozenie", tekst=="Europa zachodnia")
		Fakt(klucz=="euro", prawda)
		(or
			(and
				Fakt(klucz=="samochody", prawda)
				Fakt(klucz=="marka_samochodu", tekst in ("Opel", "BMW", "Audi", "Mercedes", "Porsche", "Volkswagen"))
			)
			Fakt(klucz=="piwo", tekst=="Paulaner")
		)
	then
		insert(new Fakt("panstwo", "Niemcy"));
end

rule "Norwegia"
	salience 10000
	when
		(or
			(and
				Fakt(klucz=="polozenie", tekst=="Europa polnocna")
				Fakt(klucz=="wladza", tekst=="Monarcha")
			)
			Fakt(klucz=="piwo", tekst=="Lysholmer")
		)
	then
		insert(new Fakt("panstwo", "Norwegia"));
end

rule "Polska"
	salience 10000
	when
		Fakt(klucz=="polozenie", tekst=="Europa wschodnia")
		Fakt(klucz=="piwo", tekst=="Tyskie")
	then
		insert(new Fakt("panstwo", "Polska"));
end

rule "Portugalia"
	salience 10000
	when
		Fakt(klucz=="polozenie", tekst=="Europa zachodnia")
		Fakt(klucz=="euro", prawda)
	then
		insert(new Fakt("panstwo", "Portugalia"));
end

rule "Rosja"
	salience 10000
	when
		Fakt(klucz=="polozenie", tekst=="Europa wschodnia")
		Fakt(klucz=="samochody", prawda)
		Fakt(klucz=="piwo", tekst=="Vodka")
	then
		insert(new Fakt("panstwo", "Rosja"));
end

rule "Rumunia"
	salience 10000
	when
		Fakt(klucz=="polozenie", tekst=="Europa wchodnia")
		Fakt(klucz=="stolica", tekst=="Bukareszt")
	then
		insert(new Fakt("panstwo", "Rumunia"));
end

rule "San Marino"
	salience 10000
	when
		Fakt(klucz=="polozenie", tekst=="Europa poludniowa")
		Fakt(klucz=="euro", prawda)
	then
		insert(new Fakt("panstwo", "San Marino"));
end

rule "Serbia"
	salience 10000
	when
		Fakt(klucz=="polozenie", tekst=="Europa poludniowa")
		(or
			Fakt(klucz=="piwo", tekst=="Jelen")
			Fakt(klucz=="stolica", tekst=="Belgrad")
		)
	then
		insert(new Fakt("panstwo", "Serbia"));
end

rule "Slowacja"
	salience 10000
	when
		Fakt(klucz=="polozenie", tekst=="Europa wschodnia")
		Fakt(klucz=="euro", prawda)
		Fakt(klucz=="piwo", tekst=="Zlaty Bazant")
	then
		insert(new Fakt("panstwo", "Slowacja"));
end

rule "Slowenia"
	salience 10000
	when
		(or
			Fakt(klucz=="piwo", tekst=="Lasko")
			Fakt(klucz=="stolica", tekst=="Lublana")
		)
	then
		insert(new Fakt("panstwo", "Slowenia"));
end

rule "Szwajcaria"
	salience 10000
	when
		Fakt(klucz=="polozenie", tekst=="Europa zachodnia")
	then
		insert(new Fakt("panstwo", "Szwajcaria"));
end

rule "Szwecja"
	salience 10000
	when
		(or
			(and
				Fakt(klucz=="polozenie", tekst=="Europa polnocna")
				Fakt(klucz=="wladza", tekst=="Monarcha")
				Fakt(klucz=="samochody", prawda)
			)
			Fakt(klucz=="szwecja", prawda)
			Fakt(klucz=="piwo", tekst=="Nils Oscar")
		)
	then
		insert(new Fakt("panstwo", "Szwecja"));
end

rule "Turcja"
	salience 10000
	when
		Fakt(klucz=="polozenie", tekst=="Europa poludniowa")
		Fakt(klucz=="trucja", prawda)
	then
		insert(new Fakt("panstwo", "Turcja"));
end

rule "Ukraina"
	salience 10000
	when
		Fakt(klucz=="polozenie", tekst=="Europa wschodnia")
	then
		insert(new Fakt("panstwo", "Ukraina"));
end

rule "Watykan"
	salience 10000
	when
		Fakt(klucz=="wladza", tekst=="Papież")
	then
		insert(new Fakt("panstwo", "Watykan"));
end

rule "Wegry"
	salience 10000
	when
		Fakt(klucz=="polozenie", tekst=="Europa wschodnia")
	then
		insert(new Fakt("panstwo", "Wegry"));
end

rule "Wielka Brytania"
	salience 10000
	when
		Fakt(klucz=="polozenie", tekst=="Europa zachodnia")
		Fakt(klucz=="wladza", tekst=="Monarcha")
		Fakt(klucz=="samochody", prawda)
		Fakt(klucz=="marka_samochodu", tekst in ("Vauxhall", "Bentley", "Rolls Royce", "Aston Martin", "Land Rover"))
	then
		insert(new Fakt("panstwo", "Wielka Brytania"));
end

rule "Wlochy"
	salience 10000
	when
		(or
			(and
				Fakt(klucz=="polozenie", tekst=="Europa poludniowa")
				Fakt(klucz=="euro", prawda)
				Fakt(klucz=="samochody", prawda)
			)
			Fakt(klucz=="piwo", tekst=="Peroni")
		)
	then
		insert(new Fakt("panstwo", "Wlochy"));
end