//created on: 2013-11-22
package rules

//list any import classes here.
import com.sample.DroolsTest.*


//declare any global variables here
import pl.put.poznan.*;



rule "Norwegia"

    when
        Odpowiedz(pytanie == "id_2", tekst == "Norweskie")
    then
        Odpowiedz.oglos("Norwegia");

end

rule "Rosja"
    //include attributes such as "salience" here...
    when
       Odpowiedz(pytanie == "id_3", prawda)
    then
       Odpowiedz.oglos("Rosja");

end

rule "Wlochy"
    //include attributes such as "salience" here...
    when
       Odpowiedz(pytanie == "id_4", prawda)
    then
       Odpowiedz.oglos("Wlochy");

end

rule "Afryka"
    //include attributes such as "salience" here...
    when
       Odpowiedz(pytanie == "id_4", !prawda)
    then
       Odpowiedz.oglos("Pewnie afryka ;)");

end